# document: https://github.com/realm/SwiftLint

# 無効にするルール
disabled_rules:
- multiple_closures_with_trailing_closure # 複数のクロージャーの場合でも、trailing closureを利用したいため
- empty_enum_arguments # enumの引数を省略したいため

# opt-inルールの中で無効にするルール
- conditional_returns_on_newline # ガード文などは簡潔に一行で記述したいため
- discouraged_optional_collection # PHImageManagerの既存仕様のため
- explicit_enum_raw_value # 暗黙的なraw値で問題ないため
- explicit_type_interface # 型推論を利用したいため
- fatal_error_message # メッセージは不要なため
- file_header # ヘッダには特に決まりがないため
- lower_acl_than_parent # 対応不可のため
- no_extension_access_modifier # extension_access_modifierを優先するため
- no_grouping_extension # グルーピングにextensionを利用したいため
- strict_fileprivate # fileprivateを利用したいため
- switch_case_on_newline # caseと同じ行に記述したいため
- trailing_closure # RxSwiftのOnNextでwarningが出るため
- trailing_whitespace
- identifier_name
- superfluous_disable_command
- class_delegate_protocol

opt_in_rules:
- anyobject_protocol
- array_init
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_first_not_nil
- discouraged_optional_collection
- empty_count
- empty_string
- empty_xctest_method
- explicit_enum_raw_value
- explicit_init
- explicit_self
- explicit_type_interface
- fallthrough
- fatal_error_message
- file_header
- file_name
- first_where
- force_unwrapping
- identical_operands
- implicit_return
- joined_default_parameter
- last_where
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- missing_docs
- modifier_order
- multiline_arguments
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- no_grouping_extension
- nslocalizedstring_key
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefixed_toplevel_constant
- private_action
- private_outlet
- prohibited_interface_builder
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- redundant_type_annotation
- required_enum_case
- single_test_class
- sorted_first_last
- sorted_imports
- static_operator
- strict_fileprivate
- strong_iboutlet
- switch_case_on_newline
- toggle_bool
- trailing_closure
- unneeded_parentheses_in_closure_argument
- unused_import
- unused_private_declaration
- vertical_parameter_alignment_on_call
- xct_specific_matcher
- yoda_condition
- weak_delegate

# Lint対象に追加するパス
included:
- ReeMap

# Lint対象から除外するパス
excluded:
- Carthage
- Pods
- ReeMapDemoTests

# 1行の文字列制限
line_length:
- 400   # warning
- 600   # error

type_body_length:
- 400
- 600

file_length:
- 500
- 1000

function_body_length:
- 100
- 200

type_name:
  min_length: 3
  max_length: 40
  excluded:
  - C
  - E
  - ui
  - UI
  - storyboard
  - file
  - image
  - _R
  - string
  - localizable
  - launchScreen
  - intern

implicitly_unwrapped_optional:
  excluded:
    - UI
    - Routing
    - ViewModel
    - DisposeBag
    - ViewController

multiline_parameters_brackets:
  excluded:
    - disposeBag
    - DisposeBag

multiline_arguments_brackets:
  excluded:
    - disposeBag

missing_docs:
  - internal