# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
app_identifier "com.gmail.g1221438.ReeMap"

# アプリ名称
name({
	'en-US' => "ReeMap",
	'ja' => "ReeMap"
})

# リリースノート
release_notes({
  'en-US' => "This is First Release.",
  'ja' => "リリースしました。"
})

# キーワード
keywords({
  'en-US' => "Reminder, Map",
	'ja' => "リマインダー,マップ"
})

# そのまま申請する場合はtrue しない場合はfalse
submit_for_review false

# スクリーンショットのアップロードをスキップする場合はtrue
skip_screenshots true

# メタデータのアップロードをスキップする場合はtrue
skip_metadata false

# バイナリーデータ(ipa,pkg)のアップロードをスキップする場合はtrue
skip_binary_upload false

# アプリの説明
# description({
#   'en-US' => "English Description here",
#   'ja' => "説明文ですよ！\n\nですよ！"
# })

# # サポートURL
# support_url({
#   'en-US' => "http://harusou-apps.com/1/",
#   'ja' => "http://harusou-apps.com/2/"
# })

# # プライバシーポリシーURL
# privacy_url({
#   'en-US' => "http://harusou-apps.com/3/",
#   'ja' => "http://harusou-apps.com/4/"
# })

# # レーティング
# app_rating_config_path "./deliver/app_rating_config.json"

# #コピーライト
# copyright "Copyright © harusou-apps.inc"

# # アプリアイコン
# app_icon './Icon-1024.png'

# 参考
# http://yokada3.hatenablog.com/entry/fastlane_deliver1_1