require 'dotenv'
Dotenv.load

fastlane_version "2.129.0"

default_platform(:ios)

platform :ios do
	PLIST_PATH = "./ReeMap/Info.plist"
  BUNDLE_ID  = get_info_plist_value(path: PLIST_PATH, key: "CFBundleIdentifier")
	VERSION    = get_info_plist_value(path: PLIST_PATH, key: "CFBundleShortVersionString")
	BUILD      = get_info_plist_value(path: PLIST_PATH, key: "CFBundleVersion")
	SCHEME     = BUNDLE_ID.include?("Develop") ? "DEVELOP" : "RELEASE"

	before_all do
		cocoapods
		ENV["SLACK_URL"] = ENV["SLACK"]
	end

	platform :ios do
		lane :test do
			scan
		end
	end



	error do |lane, exception|
		next unless Helper.is_ci?
		slack(
			message: exception.message,
			success: false
		)
	end
end
